#!/bin/bash
#
# Perform necessary varnish_rest_api setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

echo "Thank you for installing varnish_rest_api!"

exit 0
